### ISSUE TITLE
Yellow pixels line 16

### ISSUE THREAD

**Issue by venice1200** [ingloriond/MiSter_I2C_Logos#2]
Hi,
I have corrected 3 pictures with yellow pixels at line 16.

Please merge my pull-request.

**Comment by venice1200** [comment]
Thx

**Comment by ingloriond** [comment]
Thanks to you, I was climbing and from the mobile I did'nt  know how to do merge pull request hahaha I'll keep on working on logos ... still learning

________________________________
De: venice1200 ***@***.***>
Enviado: domingo, 25 de abril de 2021 16:53
Para: ingloriond/MiSter_I2C_Logos ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: Re: [ingloriond/MiSter_I2C_Logos] Yellow pixels line 16 (#2)


Thx

**Comment by venice1200** [comment]
Have you seen the XPMtoPix conversion tool. 
If not try it, less steps to do.

Nice climbing weather?

**Comment by ingloriond** [comment]
Hello!! Yes I tried and it works great. Nice job!! Yes, here in Spain the weather is almost always quite good .. And here at "la Costa del Sol" it is superb !! ;)

________________________________
De: venice1200 ***@***.***>
Enviado: domingo, 25 de abril de 2021 18:10
Para: ingloriond/MiSter_I2C_Logos ***@***.***>
Cc: ingloriond ***@***.***>; Comment ***@***.***>
Asunto: Re: [ingloriond/MiSter_I2C_Logos] Yellow pixels line 16 (#2)


Have you seen the XPMtoPix conversion tool.
If not try it, less steps to do.

Nice climbing weather?
